// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAAX2jM3g64f2IzZ9gH_CsnjfaeDpo5k',
    appId: '1:801143696197:web:aa1e4bd93338e09a916c2c',
    messagingSenderId: '801143696197',
    projectId: 'dormmanagement-16371',
    authDomain: 'dormmanagement-16371.firebaseapp.com',
    storageBucket: 'dormmanagement-16371.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTAjZAywk_YSflpDw2fNn0ZnyPEfkzfjY',
    appId: '1:801143696197:android:58f779219e4efa18916c2c',
    messagingSenderId: '801143696197',
    projectId: 'dormmanagement-16371',
    storageBucket: 'dormmanagement-16371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3KSGo4M7dv9CmB9rmploDBsS49oDxC0U',
    appId: '1:801143696197:ios:c134d303c63ec013916c2c',
    messagingSenderId: '801143696197',
    projectId: 'dormmanagement-16371',
    storageBucket: 'dormmanagement-16371.appspot.com',
    iosClientId: '801143696197-rd5ad8bm3foa7q68edrf8ms83mkqom5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.dormManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3KSGo4M7dv9CmB9rmploDBsS49oDxC0U',
    appId: '1:801143696197:ios:c134d303c63ec013916c2c',
    messagingSenderId: '801143696197',
    projectId: 'dormmanagement-16371',
    storageBucket: 'dormmanagement-16371.appspot.com',
    iosClientId: '801143696197-rd5ad8bm3foa7q68edrf8ms83mkqom5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.dormManagement',
  );
}
